### ISSUE TITLE
Issue with GetParents and SetParents

### ISSUE THREAD

**Issue by JZXPacky** [TheAlphaSchoolSystemPTYLTD/IdM#18]
Hi team,

This was logged on TASS Hub but Matthew Gray told me it had to be logged here.

We are using automation with Identity1 to manage our Staff, Student, and Parent user accounts.

In setting up the iDM API for SetParents and GetParents, we have found that when there is no LDAP/SAML table entry for the Parent record, GetParents returns the parent code as the username, event with no entry in the LDAP table.

With our setup, we use the parent code as the LDAP username, and due to it returning this in the GetParents call, it doesn’t think any changes need to be made.

Can this please be investigated, as it is not operating as expected. If there is no entry in the LDAP/SAML table for Parent Lounge, username should return NULL.

Thank you.

Luke @ St Hilda's

**Comment by leonseremelis-tass** [comment]
Presently, this represents the standard behavior. However, we will investigate this issue and provide you with a response shortly.

**Comment by CTO4556** [comment]
It never used to be standard behaviour - it was always blank, but something has changed. I just logged this with TASS Support:

When we do a getparents, each record now has “username” populated with the user_code.

We understood this to be derived from the LDAP/SAML mapping interface for parent lounge. Prior to this, the field has been blank, meaning we could distinguish that there was not parent lounge map and we needed to add one.

Why has this changed?

Chris

**Comment by leonseremelis-tass** [comment]
Hi, I have had a look at the original spec for this API and will upgrade this to a bug.

**Comment by CTO4556** [comment]
Thanks Leon,
I await an update,

Chris

**Comment by JZXPacky** [comment]
That's great news Leon, thanks for letting us know.

Cheers,
Luke.

**Comment by scottetass** [comment]
The issue has been identified and fixed. It will be released on 15th May in the 59.05.200 release.
username will be returned as empty string when not applicable.
