### ISSUE TITLE
SetAdmin not creating new TASS.Web user accounts

### ISSUE THREAD

**Issue by TKalsi** [TheAlphaSchoolSystemPTYLTD/IdM#19]
Hi TASS IDM Team,

I'm encountering an issue with the SetAdmin method. It won't let me create new TASS.Web user records. The error I am getting is "user_code is not a valid admin user code". 

I'm passing the user_code, e_mail and username details in the API Post method. 

I am able to update existing TASS.Web user records via the API method, but it won't let me create new ones. 

Mathew Gray from TASS mentioned to ask for help here. Any assistance would be greatly appreciated. 

Kind Regards,

Tegh Kalsi

**Comment by bradftass** [comment]
Hi Tegh,

I apologise for the delay.  This endpoint is working by design as it does not create new TASS.web user accounts, it simply maps a new LDAP account against an existing TASS.web user.

Kind Regards,
Brad Fleming
