### ISSUE TITLE
Detailed explanation of parameters

### ISSUE THREAD

**Issue by JZXPacky** [TheAlphaSchoolSystemPTYLTD/IdM#2]
Hi team, currently setting up the API for use with MIM. Have been talking to @sam-fisher about this, as he said there isn't anyone currently using this with MIM and I am wanting to extend on our automation.

Initial testing is good, however I am after clarification of descriptions on some of the parameters. For example, in the SetEmployee description it lists the below:

```Optional:

username [string] - username (will be used for creating new portalusers record)

e_mail [string] - Email Address

school_email [string] - School Email Address

idm [string] - idm

Conditional:

user_code [string] - Employee Code must be supplied if 'username' is not

username [string] - Employee Portal Username must be supplied if 'user_code' is not

web_access [string] - Must be "Y" or "N", only valid for teacher
```
What does the idm field update in the database? Is this the full list of parameters that are available or are there more?

Appreciate the help on this.

Cheers,
Luke @ St Hilda's.

**Comment by tassweb-fang** [comment]
Hi, 'idm' is not a valid field for 'setEmployee' and it was removed from the documentation on Nov 29, 2021.
