### ISSUE TITLE
getParents not returning students

### ISSUE THREAD

**Issue by donebydavid** [TheAlphaSchoolSystemPTYLTD/IdM#22]
TASS support has requested that I obtain support here (CS-238162)

When using the getParents function, if the family is a complex split, then the parent who has been split away returns no students listed.

The only way to have students returned listed is to add the parent into the Split Family Access table.

Example API Responses:
Original Parent Code:   PAR001
```
"PAR001": [{
    "sfa_num": "",
    "students": [
        "STUD001"
    ]
]
```

Complex Split parent, not added into SFA table
```
"PAR002": [{
    "sfa_num": "",
    "students": [
        ""
    ]
]
```

Complex Split parent after being added into SFA table
```
"PAR002": [{
    "sfa_num": "1",
    "students": [
        "STUD001"
    ]
]
```

I would not expect a complex split family to need to be added into the SFA table, as I believe this is only really needed for Simple Splits.

**Comment by scottetass** [comment]
Hi,

PAR002 does need to be given access to the appropriate students via the SFA table. Once the parent accounts are split, PAR002 loses the default relationship they had with the students as TASS can only have a default student relationship with one parent account. PAR001 retains that default relationship. So, in order for PAR002 to see the students in parent lounge (and this API's results) they need to be given access via the SFA table.
 
If you need further clarification on split families, please contact customer care, they will be able to help out there.

Thanks, Scott
