### ISSUE TITLE
 LDAP/SAML Maintenance

### ISSUE THREAD

**Issue by abass-cc** [TheAlphaSchoolSystemPTYLTD/IdM#24]
Hi Team,
I have been tasked to go through the LDAP/SAML Maintenance component in [tass.web](http://tass.web/) to remove mappings to all products of TASS to staff and parents who may no longer be at the school.

I have had a look at the API but I am not able to find a way to manage that area in bulk. I understand if you remove web access, that will stop people from being able to use those areas. However, I need to remove the mapping all together.

**Comment by scottetass** [comment]
Hi,

There is no API that will allow you to remove the mapping altogether.

You can, however, do this action in TASS.Web itself through a couple of different ways, it all depends on how many accounts you need to remove.

You can access the right area by navigating to the menu item 'System Admin > Users > LDAP/SAML Maintenance'. Once in that screen, you will see the various different products that you can control. Click View of either Parent Lounge or Teacher Kiosk.

This is where you can decide on the best method for maintaining users.

If you don't have many mappings to remove, then you can just hit the Delete button for each user from the Users tab.

If you do have a few to remove then you can use the 'CSV Upload' functionality but bear in mind that the CSV is only for _uploading_ mappings, so you will need to populate the CSV with all mappings that you want to keep and exclude from the file the ones you want to remove, then upload the CSV. This process will wipe out the entire mappings for the product and re-populate with what is in the CSV so caution is needed. The necessary columns required in the CSV can be found via online help documentation.

Thanks, Scott
