### ISSUE TITLE
getEmployees - ADD Campus attribute

### ISSUE THREAD

**Issue by DDownesK12Solutions** [TheAlphaSchoolSystemPTYLTD/IdM#25]
Currently the campus attribute is available only in the Library-Integration getEmployee API but should be included in the IdM getEmployees.

Dean

**Comment by scottetass** [comment]
Hi Dean,

An enhancement to include campus in the employee details will be implemented in release 59.10.200.
As an employee can be linked with multiple campuses, the return structure will be an array of campuses containing campus code and description.

![image](https://github.com/user-attachments/assets/a69c8212-d53c-468b-8064-462a4933c17e)


Thaks, Scott

**Comment by DDownesK12Solutions** [comment]
Thats fantastic thanks Scott!

D
________________________________
