### ISSUE TITLE
Unable to add admin user

### ISSUE THREAD

**Issue by HannaAzzi** [TheAlphaSchoolSystemPTYLTD/IdM#26]
I'm trying to add a admin user.  The call returns an error 

**call**
$appCode     = 'LKID'
$companyCode = '99'
$apiVersion  = '3'
$method      = "setAdmin"
$endpoint    = "https://loreto.nsw.tass.cloud/tassweb/api/"
$parameters  = '{"user_code":"0000001","e_mail":"TEST01@LORETO.NSW.EDU.AU"}'

**Here is the error**
{
    "__status": "invalid",
    "__forms": {},
    "__tassversion": "01.059.08.200",
    "__invalid": {
        "user_code": "user_code is not a valid admin user code."
    },
    "__locks": {},
    "token": {
        "user_code": "0000001",
        "timestamp": "{ts '2024-09-20 08:09:42'}",
        "e_mail": "TEST01@LORETO.NSW.EDU.AU"
    }
}

**Code is in Employee table as returned by getEmployee**
{
            "initials": "HA",
            "suffix": "",
            "surname": "Test",
            "is_teacher": "N",
            "tch_code": "",
            "ceider": "",
            "end_date": "",
            "start_date": "2024-09-01 00:00:00.0",
            "e_mail": "",
            "departments": "",
            "school_email": "",
            "person_num": 4195,
            "first_name": "Hanna",
            "web_access": false,
            "user_code": "0000001",
            "salutation": "",
            "preferred_name": "Hanna",
            "other_name": "",
            "username": "",
            "title": "Mr"
        },

**Comment by scottetass** [comment]
Hi,

Employees cannot be granted administrator privileges to TASS.

Administrator logons can only be created via System Admin / Users / User Maintenance screen and then you can allocate the necessary permissions for that user.

Thanks, Scott

**Comment by HannaAzzi** [comment]
I'm an employee and I've been assigned an admin role.
What does setAdmin do?
Is the error I'm getting misleading?
What I'm doing wrong?
