### ISSUE TITLE
idM Api Schema for Rest API calls

### ISSUE THREAD

**Issue by akaddo** [TheAlphaSchoolSystemPTYLTD/IdM#6]
Dear All,
I want to link TASS to Intelledox(SmartIQ) to read data from TASS via API.
I know that Intelledox allows Rest data connection like in this documentation(https://knowledgehub.intelledox.com/docs/rest-1#section-get-method); however, since their system needs a schema.json file to be created first, they asked me to check with you guys.
I would appreciate if you can please refer me to the TASS different APIs' schema files, or a guide to creating one.
Your prompt attention to this is greatly appreciated.

**Comment by bradftass** [comment]
Hi, at this stage API schema JSON files do not exist and are not on our current roadmap to implement.  Our GitHub documentation is the best source of information.
