### ISSUE TITLE
getParents not returning correct email addresses

### ISSUE THREAD

**Issue by cwool** [TheAlphaSchoolSystemPTYLTD/IdM#8]
I have been testing this with Waverley College and we have noticed that incorrect addresses are being returned.

Example:

{
            "200032": {
                "web_access": true,
                "user_code": 200032,
                "person2": {
                    "initials": "",
                    "suffix": "",
                    "surname": "A*******",
                    "description": "Father",
                    "preferred_name": "T****",
                    "other_name": "",
                    "title": "",
                    "e_mail": "",
                    "first_name": "T****"
                },
                "address": {
                    "1": {
                        "email": "mothersemail@outlook.com"
                    },
                    "4": {
                        "email": "mothersemail@outlook.com"
                    },
                    "5": {
                        "email": ""
                    },
                    "8": {
                        "email": ""
                    }
                },
                "person1": {
                    "initials": "",
                    "suffix": "",
                    "surname": "A*******",
                    "description": "Mother",
                    "preferred_name": "A*****",
                    "other_name": "",
                    "title": "",
                    "e_mail": "",
                    "first_name": "A******"
                },
                "username": 200032,
                "sfa_num": "",
                "students": [
                    100006,
                    100005
                ]
            }
        },

From the example you can see it's a happy nuclear family. The father's address "5" has an email that is not being returned and we are only getting the first email returned as email, instead of email1 and email2. School's TASS.web Version is
01.054.4.000

**Comment by bradftass** [comment]
Hi, this issue has been resolved in v54.4.121.  Documentation has been updated to suit:
https://github.com/TheAlphaSchoolSystemPTYLTD/IdM/blob/master/GetParents.md
